service: btgservice
frameworkVersion: '3'

provider: 
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

plugins: 
  - serverless-s3-sync

custom:
  sitename: blacktechiegirl.xyz
  s3Sync:
    - bucketName: ${self:custom.sitename}
      localDir: frontend/build

resources: 
  Resources: 
    BtgFrontend:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.sitename}
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    BtgFrontendPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: BtgFrontend
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "arn:aws:iam::366325825078:user/BtgUser"
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.sitename}/*
                  
    CloudFrontDistribution:
            Type: AWS::CloudFront::Distribution
            Properties:
                DistributionConfig:
                    Origins:
                        - DomainName: ${self:custom.sitename}.s3.amazonaws.com
                          Id: ReactApp
                          CustomOriginConfig:
                              HTTPPort: 80
                              HTTPSPort: 443
                              OriginProtocolPolicy: https-only
                    Enabled: 'true'
                    DefaultRootObject: index.html
                    CustomErrorResponses:
                        - ErrorCode: 404
                          ResponseCode: 200
                          ResponsePagePath: /index.html
                    DefaultCacheBehavior:
                        AllowedMethods:
                            - DELETE
                            - GET
                            - HEAD
                            - OPTIONS
                            - PATCH
                            - POST
                            - PUT
                        TargetOriginId: ReactApp
                        ForwardedValues:
                            QueryString: 'false'
                            Cookies:
                                Forward: none
                        ViewerProtocolPolicy: redirect-to-https
                    ViewerCertificate:
                        CloudFrontDefaultCertificate: true

    

